name: Update combined blocklist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: pip3 install -U requests

      - name: build blocklist
        run: python3 listGenerator.py
        
      - name: setup git config
        run: |
          git config user.name "Blocklist Updater Bot"
          git config user.mail "<>"
          
      - name: commit new blocklist
        run: |
          git add blocklist.txt
          git commit -m "update blocklist"
          git push origin master
