name: Update combined blocklist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: pip3 install -U requests

      - name: build blocklist
        run: python3 listGenerator.py
        
      - name: upload as release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "blocklist.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
